# Generated by Django 5.0.3 on 2024-03-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=3)),
                ('cardholder_name', models.CharField(max_length=100)),
            ],
        ),
    ]
