# Generated by Django 5.0.3 on 2024-03-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_creditcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
